# Generated by Django 5.1.5 on 2025-01-27 07:25

import autoslug.fields
import novels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0007_alter_updateday_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อเรื่อง')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Slug')),
                ('author', models.CharField(max_length=255, verbose_name='ผู้แต่ง')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('image', models.ImageField(upload_to=novels.models.content_covers, verbose_name='รูปภาพปก')),
                ('copyright', models.CharField(choices=[('มีลิขสิทธิ์', 'มีลิขสิทธิ์'), ('ยังไม่มีลิขสิทธิ์', 'ยังไม่มีลิขสิทธิ์')], default='ยังไม่มีลิขสิทธิ์', max_length=255, verbose_name='ลิขสิทธิ์')),
                ('status', models.CharField(choices=[('จบแล้ว', 'จบแล้ว'), ('ยังไม่จบ', 'ยังไม่จบ'), ('หยุดชั่วคราว', 'หยุดชั่วคราว'), ('กำลังฉาย', 'กำลังฉาย')], default='กำลังฉาย', max_length=255, verbose_name='สถาณะเรื่องนี้')),
                ('price', models.PositiveIntegerField(verbose_name='ราคาขายต่อตอน')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='จำการกดถูกใจ')),
                ('viewer', models.PositiveIntegerField(default=0, verbose_name='จำนวนคนอ่าน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateField(verbose_name='วันเวลาเปิดให้อ่าน')),
                ('category', models.ManyToManyField(to='novels.category', verbose_name='หมวดหมู่')),
                ('tags', models.ManyToManyField(to='novels.tags', verbose_name='แท็ก')),
                ('update_days', models.ManyToManyField(blank=True, to='novels.updateday', verbose_name='วันที่อัปเดต')),
            ],
            options={
                'verbose_name': 'การ์ตูน',
                'verbose_name_plural': 'การ์ตูน',
                'db_table': 'comics',
            },
        ),
    ]
