# Generated by Django 5.1.5 on 2025-01-22 15:31

import autoslug.fields
import django.db.models.deletion
import novels.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.CharField(max_length=255, verbose_name='คำอธิบายเพิ่มเติม')),
                ('update_ad', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อแท็ก')),
                ('description', models.CharField(max_length=255, verbose_name='คำอธิบายเพิ่มเติม')),
                ('update_ad', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'แท็ก',
                'verbose_name_plural': 'แท็ก',
                'db_table': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Novels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อเรื่อง')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Slug')),
                ('author', models.CharField(max_length=255, verbose_name='ผู้แต่ง')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('image', models.ImageField(upload_to=novels.models.content_covers, verbose_name='รูปภาพปก')),
                ('copyright', models.CharField(choices=[('มีลิขสิทธิ์', 'มีลิขสิทธิ์'), ('ยังไม่มีลิขสิทธิ์', 'ยังไม่มีลิขสิทธิ์')], default='ยังไม่มีลิขสิทธิ์', max_length=255, verbose_name='ลิขสิทธิ์')),
                ('status', models.CharField(choices=[('จบแล้ว', 'จบแล้ว'), ('ยังไม่จบ', 'ยังไม่จบ'), ('หยุดชั่วคราว', 'หยุดชั่วคราว'), ('กำลังฉาย', 'กำลังฉาย')], default='กำลังฉาย', max_length=255, verbose_name='สถาณะเรื่องนี้')),
                ('price', models.PositiveIntegerField(verbose_name='ราคาขายต่อตอน')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='จำการกดถูกใจ')),
                ('viewer', models.PositiveIntegerField(default=0, verbose_name='จำนวนคนอ่าน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_ad', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateField(verbose_name='วันเวลาเปิดให้อ่าน')),
                ('category', models.ManyToManyField(to='novels.category', verbose_name='หมวดหมู่')),
                ('tags', models.ManyToManyField(to='novels.tags', verbose_name='แท็ก')),
            ],
            options={
                'verbose_name': 'นิยาย',
                'verbose_name_plural': 'นิยาย',
                'db_table': 'novels',
            },
        ),
        migrations.CreateModel(
            name='ChapterNovels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อตอน')),
                ('content', tinymce.models.HTMLField(verbose_name='เนื้อหา')),
                ('order', models.PositiveIntegerField(verbose_name='ลำดับตอน')),
                ('is_locked', models.BooleanField(default=True, verbose_name='ล็อกตอนนี้หรือไม่')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='จำการกดถูกใจ')),
                ('viewer', models.PositiveIntegerField(default=0, verbose_name='จำนวนคนอ่าน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novels', verbose_name='นิยาย')),
            ],
            options={
                'verbose_name': 'ตอน',
                'verbose_name_plural': 'ตอน',
                'db_table': 'chapters',
                'ordering': ['order'],
            },
        ),
    ]
