# Generated by Django 5.1.5 on 2025-01-22 15:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_alter_chapternovels_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapternovels',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='content'),
        ),
    ]
