# Generated by Django 5.1.5 on 2025-01-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_alter_chapternovels_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'วันจันทร์'), ('tue', 'วันอังคาร'), ('wed', 'วันพุธ'), ('thu', 'วันพฤหัสบดี'), ('fri', 'วันศุกร์'), ('sat', 'วันเสาร์'), ('sun', 'วันอาทิตย์')], max_length=3, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='novels',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.AlterModelTable(
            name='chapternovels',
            table='chapters_novel',
        ),
        migrations.AddField(
            model_name='novels',
            name='update_days',
            field=models.ManyToManyField(blank=True, to='novels.updateday', verbose_name='วันที่อัปเดต'),
        ),
    ]
