# Generated by Django 5.1.5 on 2025-01-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_updateday_rename_update_ad_novels_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updateday',
            options={'verbose_name': 'ตารางอัพเดท', 'verbose_name_plural': 'ตารางอัพเดท'},
        ),
        migrations.AlterModelTable(
            name='updateday',
            table='update_day',
        ),
    ]
