# Generated by Django 5.1.5 on 2025-01-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_updateday_options_alter_updateday_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updateday',
            options={'verbose_name': 'ตารางอัปเดต', 'verbose_name_plural': 'ตารางอัปเดต'},
        ),
    ]
