# Generated by Django 5.1.5 on 2025-01-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_alter_updateday_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updateday',
            options={'ordering': ['day'], 'verbose_name': 'ตารางอัปเดต', 'verbose_name_plural': 'ตารางอัปเดต'},
        ),
    ]
